title: <p align="center"> Juan Manuel Corbera  </p>
logo: "/images/logo.png?raw=true"
description: > 
  <p align="center">
  <a href="pdf/CV_CorberaJuanManuel.pdf">CV</a> |
  <a href="https://github.com/jmcorbera">GitHub</a>
  </p>
  
  <p align="justify">
  Team Leader, Full Stack Developer. More than 15 years offering IT solutions. 
  <br><br> 
  Passionate about what I do, constantly growing, looking for innovation in each step.<br>
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
