title: <p align="center"> Juan Manuel Corbera  </p>
logo: "/images/logo.png?raw=true"
description: > 
  <p align="center">
  <a href="pdf/resume.pdf">CV</a> ||
  <a href="https://github.com/jmcorbera">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in Business Analytics at Simon Business School, University of Rochester.
  <br><br>
  I am currently a Machine Learning Research Intern at Skim AI Technologies with a focus on NLP and Deep Learning research.
  <br><br>
  </p>

  <p align="justify">
  Full Stack Developer. More than 15 years offering IT solutions. 
  <br><br> 
  Passionate about what I do, constantly growing, looking for innovation in each step.<br>
  Second description
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
